name: Build
on: 
  push:
    branches:
      - release
env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  FILE_NAME: "FavoritesAsset"
jobs:
  createUnityPackage:
    name: Create UnityPackage for ${{ matrix.targetPlatform }} on version ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - .
        unityVersion:
          - 2019.4.14f1
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true

      # Cache
      - name: Cache
        uses: actions/cache@v2
        with:
          path: Library
          key: Library-Release
          restore-keys: Library-

      # Build
      - name: Build package
        id: build
        uses: webbertakken/unity-builder@v2
        with:
          buildName: ${{ env.FILE_NAME }}.unitypackage
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          buildMethod: CI.Builder.Build
          versioning: None

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ env.FILE_NAME }}.unitypackage
          path: ${{ env.FILE_NAME }}.unitypackage
