name: CI-Build
on: 
  push:
    tags:
      - '*'
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
  PROJECT_ROOT: .
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  with:
    tag_name: ${{ github.ref }}
    release_name: ${{ github.ref }}
    draft: false
    prerelease: false
jobs:
  createUnityPackage:
    name: Create UnityPackage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - uses: actions/cache@v1.1.0
        with:
          path: ${{ env.PROJECT_ROOT }}/Library
          key: Library-${{ env.PROJECT_ROOT }}

      - name: Get Unity editor version
        id: getUnityEditorVersion
        uses: CumulusDS/get-yaml-paths-action@v0.1.0
        with:
          file: ${{ env.PROJECT_ROOT }}/ProjectSettings/ProjectVersion.txt
          versionOutput: m_EditorVersion

      - uses: webbertakken/unity-builder@v1.0
        with:
          unityVersion: ${{ steps.getUnityEditorVersion.outputs.versionOutput }}
          projectPath: ${{ env.PROJECT_ROOT }}
          buildMethod: CI.Builder.Build

      - uses: actions/upload-artifact@v1
        with:
          name: FavoritesAsset.unitypackage
          path: FavoritesAsset.unitypackage
      
      - name: Upload Release Asset
        uses: actions/upload-release-asset@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: FavoritesAsset.unitypackage
          asset_name: FavoritesAsset.unitypackage
          asset_content_type: application/gzip